import fs from "node:fs";
import path from "node:path";
import { parseDeclarativeSchema } from "../src/schema/sdl_adapter.js";
import { schemaSnapshotFromDeclarative } from "../src/schema/uiSchema.js";
import { openSQLite, materializeSchema } from "../src/runtime/database.js";
import { executeScript, executeQueryWithTrace } from "../src/runtime/engine.js";

const dir = path.join(import.meta.dirname, "../tests/schemas");
const read = (f: string) => fs.readFileSync(path.join(dir, f), "utf8");
const strip = (s: string) => s.replace(/#[^\n]*/g, "");
const wrap = (m: string, s: string) => strip(s).trimStart().startsWith("module ") ? strip(s) : `module ${m} {\n${strip(s)}\n}`;
const decl = parseDeclarativeSchema(wrap("default", read("cards.esdl")), { legacySyntaxCompat: true });
const schema = schemaSnapshotFromDeclarative(decl);
const { db } = openSQLite();
materializeSchema(db, schema);
executeScript(db, schema, read("cards_setup.edgeql"), undefined, { defaultModule: "default" });
const q = process.argv[2] ?? "select 1";
const t: any = executeQueryWithTrace(db, schema, q, {});
const trace = t.traces?.[0] ?? t;
console.log("SQL:", (trace.sql?.sql ?? "").slice(0, 1200));
console.log("ROWS:", JSON.stringify(trace.result?.rows, null, 1)?.slice(0, Number(process.env.ROWS_MAX ?? 2000)));
