import fs from "node:fs";
import path from "node:path";
import { parseDeclarativeSchema } from "../src/schema/sdl_adapter.js";
import { schemaSnapshotFromDeclarative } from "../src/schema/uiSchema.js";
import { parseEdgeQL } from "../src/edgeql/parser.js";
import { getCompilerService } from "../src/compiler/service.js";
const dir = path.join(import.meta.dirname, "../tests/schemas");
const read = (f: string) => fs.readFileSync(path.join(dir, f), "utf8");
const strip = (s: string) => s.replace(/#[^\n]*/g, "");
const decl = parseDeclarativeSchema(`module default {\n${strip(read("cards.esdl"))}\n}`, { legacySyntaxCompat: true });
const schema = schemaSnapshotFromDeclarative(decl);
const ast: any = parseEdgeQL(process.argv[2] ?? "select 1");
const stmt = Array.isArray(ast) ? ast[0] : ast;
const compiled: any = getCompilerService().compile(schema, stmt, {} as any);
const g = compiled.gelIr;
const subject = g?.subject ?? g?.expr;
let cursor = subject;
while (cursor?.expr?.kind === "select_expr") cursor = cursor.expr.result;
console.log("cursor kind:", cursor?.expr?.kind, "named:", cursor?.expr?.named);
console.log("elements:", JSON.stringify((cursor?.expr?.elements ?? []).map((e: any) => ({ name: e.name, kind: e.val?.expr?.kind })), null, 1));
console.log("byAtoms:", g?.byAtoms, "hidden:", g?.hiddenByFields);
